#
# Module manifest for module 'PsISEProjectExplorer'
#
# Generated by: Marcin Grzywa
#
# Generated on: 07.04.2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PsISEProjectExplorer.psm1'

# Version number of this module.
ModuleVersion = '1.4.0'

# ID used to uniquely identify this module
GUID = '442c24ec-44fc-4786-ad63-30a39eec6b7b'

# Author of this module
Author = 'Marcin Grzywa'

# Company or vendor of this module
CompanyName = 'Marcin Grzywa'

# Copyright statement for this module
Copyright = '2015, MIT license'

# Description of the functionality provided by this module
Description = 'Provides a tree view that enables to index and explore whole directory structure containing Powershell scripts.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = 'Windows PowerShell ISE Host'

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Add-PsISEProjectExplorerToIseProfile', 'Get-PsISEProjectExplorerControlHandle')

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @('PsISEProjectExplorer.psm1')

# List of all files packaged with this module
FileList = @('PsISEProjectExplorer.psm1', 
           'PsISEProjectExplorer.psd1', 
           'PsISEProjectExplorer.dll', 
           'PsISEProjectExplorerPS5.dll', 
           'Lucene.Net.dll', 
           'NLog.dll')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'ISE','Addon'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/mgr32/PsISEProjectExplorer/blob/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/mgr32/PsISEProjectExplorer'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}